"""add health_profiles table

Revision ID: 56622456a6dd
Revises: aa0477a874d7
Create Date: 2026-05-11 23:12:56.897525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56622456a6dd'
down_revision: Union[str, Sequence[str], None] = 'aa0477a874d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), sa.Computed('round(CAST(weight_kg / CAST(pow(height_cm / CAST(100 AS NUMERIC), 2) AS NUMERIC) AS NUMERIC), 3)', ), nullable=True),
    sa.Column('activity_level', sa.String(length=30), nullable=True),
    sa.Column('pregnancy_status', sa.String(length=30), nullable=True),
    sa.Column('allergies', sa.String(length=500), nullable=True),
    sa.Column('temperature_f', sa.Float(), nullable=True),
    sa.Column('bp_systolic', sa.Integer(), nullable=True),
    sa.Column('bp_diastolic', sa.Integer(), nullable=True),
    sa.Column('blood_sugar', sa.Float(), nullable=True),
    sa.Column('symptoms', sa.JSON(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_profiles_user_id'), 'health_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_profiles_user_id'), table_name='health_profiles')
    op.drop_table('health_profiles')
    # ### end Alembic commands ###
