"""Add FoodItem

Revision ID: d1f85a3133f5
Revises: a1b2c3d4e5f6
Create Date: 2026-05-20 10:58:07.443245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1f85a3133f5'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_bn', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('serving', sa.String(length=100), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.Column('price_bdt', sa.String(length=50), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_items_category'), 'food_items', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_items_category'), table_name='food_items')
    op.drop_table('food_items')
    # ### end Alembic commands ###
